return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  config = function()
      require('nvim-treesitter').install({
          'arduino',
          'bash',
          'c',
          'caddy',
          'cmake',
          'comment',
          'cpp',
          'css',
          'csv',
          'diff',
          'dockerfile',
          'gitignore',
          'html',
          'ini',
          'json',
          'lua',
          'make',
          'markdown',
          'nginx',
          'passwd',
          'python',
          'requirements',
          'toml',
          'yaml',
      })
  end,
}
